# ============================================================
# ML TRAINING PIPELINE FOR GENETIC CARRIER PREDICTION
# ============================================================

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score
import joblib

# ------------------------------------------------------------
# 1. Load synthetic dataset
# ------------------------------------------------------------

# This CSV is generated by generate_data.py
data = pd.read_csv("synthetic_genetic_data.csv")

print("Dataset loaded successfully")
print(data.head())

# ------------------------------------------------------------
# 2. Separate features (X) and label (y)
# ------------------------------------------------------------

X = data[
    [
        "affected_self",
        "affected_parent",
        "affected_sibling",
        "affected_child",
        "generation",
    ]
]

y = data["carrier"]

# ------------------------------------------------------------
# 3. Split data into training and testing sets
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

# ------------------------------------------------------------
# 4. Train ML model (Logistic Regression)
# ------------------------------------------------------------

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

print("Model training completed")

# ------------------------------------------------------------
# 5. Evaluate the model
# ------------------------------------------------------------

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

accuracy = accuracy_score(y_test, y_pred)
auc = roc_auc_score(y_test, y_prob)

print("Model Accuracy:", accuracy)
print("ROC AUC Score:", auc)

# ------------------------------------------------------------
# 6. Save trained model
# ------------------------------------------------------------

joblib.dump(model, "carrier_model.pkl")

print("Model saved as carrier_model.pkl")
